#!/usr/bin/env ruby

require 'fileutils'

if ARGV.length < 1
  puts "build <verson> [<version>...]"
  exit 1
end

ARGV.each do |version|
  source = "./tmp/Source#{version}"
  destination = "../deploy/Version#{version}/"


  FileUtils.rm_r source if File.exist?(source)
  FileUtils.rm_r destination if File.exist?(destination)

  FileUtils.mkdir_p source

  %w{_config.yml _includes _layouts _sass 404.html assets}.each do |d|
    FileUtils.ln_s(d, File.join(source, d), relative: true)
  end

  Dir["../build/Version#{version}/*"].each do |d|
    FileUtils.ln_s(File.expand_path(d), File.join(source, File.basename(d)))
  end

  system("bundle exec jekyll build -s #{source} --config ./_config.yml,#{source}/_config_version.yml -b /Version#{version} -d #{destination}")

  FileUtils.ln_s(File.expand_path(File.join("..", "Version#{version}", "MTConnectSysMLModel.xml")), File.join(destination, "MTConnectSysMLModel.xml"))
end